name: CI

on:
  workflow_dispatch:

jobs:
  sync:
    name: Sync Submodules
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Git Submodule Update
      run: |
        git submodule foreach "git fetch origin; git checkout master; git pull --no-rebase  origin master"

    - name: Commit update
      run: |
        git config --global user.name 'SysFlow'
        git config --global user.email 'sysflow@noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git commit -am "Auto updated submodule references" && git push || echo "No changes to commit"
